### ISSUE TITLE
官方 docker-compose.yaml 部署，无法正常访问数据库，logs 如下

### ISSUE THREAD

**Issue by yeslinyh** [didi/xiaoju-survey#461]
# 环境
OS: `debian-12.7 [x86_64]`
docker: `Docker Compose version v2.29.7`

# docker-compose.yaml

````yaml
version: "3.6"

services:
  mongo:
    image: mongo:4
    container_name: xiaoju-survey-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /mnt/nfs/docker/xiaoju-survey/mongo/db:/data/db
      - /mnt/nfs/docker/xiaoju-survey/mongo/configdb/:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
    networks:
      - xiaoju-survey

  xiaoju-survey:
    image: xiaojusurvey/xiaoju-survey:1.3.0-slim
    container_name: xiaoju-survey
    restart: always
    ports:
      - 8082:80
    environment:
      XIAOJU_SURVEY_MONGO_URL: mongodb://admin:admin@xiaoju-survey-mongo:27017
    links:
      - mongo:mongo
    depends_on:
      - mongo
    networks:
      - xiaoju-survey

volumes:
  mongo-volume:

networks:
  xiaoju-survey:
    name: xiaoju-survey
````

# logs
## xiaoju-survey

````logs
[Nest] 30  - 12/10/2024, 1:12:21 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
MongoServerSelectionError: connect ECONNREFUSED 172.24.0.2:27017
    at Timeout._onTimeout (/xiaoju-survey/server/node_modules/mongodb/lib/sdam/topology.js:278:38)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
````

## 具体表现

* 可正常进入 web 页面注册账号，且多次点注册后显示`该用户已存在`
![](https://cdn.pcdiy.xyz/2024/12/10/a74388ab5134bd58ea9d291f2a0ee3e9.png)

* 但点击登录无反应，无法进入后台
